---
- name: "Create Xvfb deamon script (systemv)"
  become: true
  ansible.builtin.template:
    src: init-xvfb.j2
    dest: /etc/init.d/xvfb
    mode: 0755

- name: "Configure Xvfb automatic startup < 16.04 (systemv)"
  become: true
  ansible.builtin.service:
    name: xvfb
    pattern: /usr/bin/Xvfb
    enabled: !!str yes
    state: started

